services:
  - type: web
    name: signature-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-file=- --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    autoDeploy: true
    healthCheckPath: /
